# Nossis Docs, serverless hosting for static, private web sites
#
# Copyright (C) 2024-2025  Matthew X. Economou
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program.  If not, see
# <https://www.gnu.org/licenses/>.

# Ignore temporary files/folders, but note that this doesn't always
# work.  Check each linter's documentation for any required
# tool-specific exclusions; cf. https://stackoverflow.com/a/75560858.
exclude: |-
  (?x)^(
      .external_modules.*|
      .terraform.*|
      build.*|
      dist.*
  )$

repos:
  # Ensure commit messages use Conventional Commits formatting;
  # see also .commitlintrc.js.
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Check shell scripts, limiting output to errors and warnings.
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]

  # Check GitHub Actions workflows.
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  # Check Python syntax.
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          # Keep the list of flake8 plugins in sync with
          # pyproject.toml.
          - dlint
          - flake8-bandit
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-eradicate
          - flake8-fixme
          - flake8-future-import
          - flake8-pytest-style
          - flake8-requirements

  # Sort Python imports.
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  # Reformat Python code after sorting imports.
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  # Lint/reformat the OpenTofu module.
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.2.1
    hooks:
      - id: tofu_validate
      - id: tofu_fmt
      - id: tofu_docs
      - id: tofu_tflint
      - id: tofu_checkov
        args:
          - --args=--download-external-modules true
          - --args=--quiet
          - --args=--skip-path .terraform
          - --args=--skip-path build
          - --args=--skip-path builds
          - --args=--skip-path dist
          - --args=--skip-path dist-lambda
      - id: tofu_trivy
        args:
          - --args=--skip-dirs .external_modules
          - --args=--skip-dirs .terraform
          - --args=--skip-dirs build
          - --args=--skip-dirs builds
          - --args=--skip-dirs dist
          - --args=--skip-dirs dist-lambda
      # - id: terrascan
      # - id: infracost_breakdown
